version: '2'

services:
    user-input-dc:
        extends:
            file: user_input_dc/app.yml
            service: app
        networks:
            internal:
                aliases:
                    - user-input-dc.docker.local
        logging:
                driver: syslog
                options:
                        tag: docker-user-input-dc
        restart: unless-stopped
        depends_on:
            - "mqtt_broker"
    locations-sds:
        extends:
            file: locations_sds/app.yml
            service: dev
        networks:
            internal:
                aliases:
                    - locations-sds.docker.local
        logging:
                driver: syslog
                options:
                        tag: docker-locations-sds
        restart: unless-stopped
        env_file:
            - django_secret_key 
            - default_password
    identity-sds:
        extends:
            file: identity_sds/app.yml
            service: app
        networks:
            internal:
                aliases:
                    - identity-sds.docker.local
        logging:
                driver: syslog
                options:
                        tag: docker-identity-sds
        restart: unless-stopped
        env_file:
            - django_secret_key 
            - default_password

    mqtt_broker:
        extends:
            file: mqtt_broker/app.yml
            service: app
        networks:
            internal:
                aliases:
                    - mqtt.docker.local
        logging:
                driver: syslog
                options:
                        tag: docker-mqtt-broker
        restart: unless-stopped
    dashboard:
        extends:
            file: dashboard_ui/app.yml
            service: app
        networks:
            internal:
                aliases:
                    - dashboard-ui.docker.local
        logging:
                driver: syslog
                options:
                        tag: docker-dashboard-ui
        restart: unless-stopped
        depends_on:
            - "mqtt_broker"

    barcode-1:
        extends:
            file: barcode_dc/app.yml
            service: app
        networks:
            internal:
                aliases:
                    - bs1.docker.local
        logging:
            driver: syslog
            options:
                tag: docker-barcode-1
        restart: unless-stopped
        environment:
            - USER_CONFIG_FILE=./config/config_1.toml
    
    barcode-2:
        extends:
            file: barcode_dc/app.yml
            service: app
        networks:
            internal:
                aliases:
                    - bs2.docker.local
        logging:
            driver: syslog
            options:
                tag: docker-barcode-2
        restart: unless-stopped
        environment:
            - USER_CONFIG_FILE=./config/config_2.toml

    barcode-3:
        extends:
            file: barcode_dc/app.yml
            service: app
        networks:
            internal:
                aliases:
                    - bs3.docker.local
        logging:
            driver: syslog
            options:
                tag: docker-barcode-3
        restart: unless-stopped
        environment:
            - USER_CONFIG_FILE=./config/config_3.toml

    barcode-4:
        extends:
            file: barcode_dc/app.yml
            service: app
        networks:
            internal:
                aliases:
                    - bs4.docker.local
        logging:
            driver: syslog
            options:
                tag: docker-barcode-4
        restart: unless-stopped
        environment:
            - USER_CONFIG_FILE=./config/config_4.toml

networks:
    internal:
        name: shoestring-internal
