[input.scanner]
serial="0581_011c"
connection_point=["0","1.3.1"]
platform = "fd500000.pcie-pci-0000:01:00.0"

[[variable]]
    name="location"
    type="static"
    value="loc@1"

[[variable]]
    name="barcode"
    type="single"
    pattern='\s*(.*)\s*'
