# Generated by Django 3.2.16 on 2025-08-20 10:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0005_auto_20250721_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='productioneventinput',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 20, 11, 57, 28, 323760)),
            preserve_default=False,
        ),
    ]
