{% if enabled_value == true %}
module_enabled = true
{% else %}
module_enabled = false
{% endif %}


[variable.location]
    name="location"
    type="static"
    value="{{location_value}}"
