# Generated by Django 3.2.16 on 2023-11-01 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0003_event'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name_plural': 'Event Records'},
        ),
    ]
