# Generated by Django 5.0.6 on 2024-08-27 13:52

import identity_manager.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity_manager', '0002_auto_20231001_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identifierpattern',
            name='defaults',
            field=models.JSONField(default=identity_manager.models.default_pattern, help_text='default/constant identity values - used if not extracted by pattern'),
        ),
        migrations.AlterField(
            model_name='identifierpattern',
            name='pattern',
            field=models.CharField(default='(?P<name>.*)', help_text='Regex pattern to extract details from barcode', max_length=50),
        ),
    ]
