# Generated by Django 3.2.16 on 2025-07-21 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0004_alter_event_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionEvent',
            fields=[
                ('event_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('item_id', models.CharField(max_length=32)),
                ('location_link', models.CharField(max_length=32)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'Production Event Records',
            },
        ),
        migrations.RenameModel(
            old_name='Event',
            new_name='TransferEvent',
        ),
        migrations.AlterModelOptions(
            name='transferevent',
            options={'verbose_name_plural': 'Transfer Event Records'},
        ),
        migrations.CreateModel(
            name='ProductionEventInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=32)),
                ('location_link', models.CharField(max_length=32)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('production_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inputs', to='state.productionevent')),
            ],
        ),
    ]
