# Generated by Django 3.2.16 on 2025-08-21 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0006_productioneventinput_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionevent',
            name='from_location_link',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
