# Generated by Django 5.0.6 on 2025-12-03 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("state", "0007_productionevent_from_location_link"),
    ]

    operations = [
        migrations.CreateModel(
            name="Setting",
            fields=[
                (
                    "key",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("value", models.CharField(max_length=256)),
            ],
            options={
                "verbose_name_plural": "Settings",
            },
        ),
    ]
