# Generated by Django 5.0.6 on 2025-12-16 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("state", "0008_settings"),
    ]

    operations = [
        migrations.CreateModel(
            name="Status",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("label", models.CharField(max_length=64)),
                ("icon", models.CharField(blank=True, max_length=64, null=True)),
                ("color", models.CharField(blank=True, max_length=16, null=True)),
            ],
            options={
                "verbose_name_plural": "Available Statuses",
            },
        ),
        migrations.CreateModel(
            name="Note",
            fields=[
                ("note_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("item_id", models.CharField(max_length=32)),
                (
                    "location_link",
                    models.CharField(blank=True, max_length=32, null=True),
                ),
                ("timestamp", models.DateTimeField()),
                ("text", models.TextField()),
            ],
            options={
                "verbose_name_plural": "Notes",
                "indexes": [
                    models.Index(fields=["item_id"], name="note_item_idx"),
                    models.Index(fields=["location_link"], name="note_loc_link_idx"),
                    models.Index(fields=["-timestamp"], name="note_timestamp_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ItemStatus",
            fields=[
                ("auto_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("item_id", models.CharField(max_length=32)),
                (
                    "location_link",
                    models.CharField(blank=True, max_length=32, null=True),
                ),
                ("timestamp", models.DateTimeField()),
                (
                    "status",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="state.status",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Item Status Records",
                "indexes": [
                    models.Index(fields=["item_id"], name="item_status_item_idx"),
                    models.Index(
                        fields=["location_link"], name="item_status_loc_link_idx"
                    ),
                    models.Index(
                        fields=["-timestamp"], name="item_status_timestamp_idx"
                    ),
                ],
            },
        ),
    ]
